/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Pow {
    public static int pow(int a, int b) {
        int r = 1;
        while (b > 0) {
            if ((b & 1) != 0) r *= a;
            a *= a;
            b >>= 1;
        }
        return r;
    }

    public static void main(String[] args) {

    }
}
