/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameter;
import org.junit.runners.Parameterized.Parameters;

import java.util.Arrays;
import java.util.Collection;

import static org.junit.Assert.*;

@RunWith(Parameterized.class)
public class PowJUnitTest {

    @Parameters
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][]{
                {1, 1, 1},
                {1, 0, 1},
                {2, 0, 1},
                {0, 0, 1},
                {0, 1, 0},
                {-3, 0, 1},
                {2, 2, 4},
                {5, 3, 125},
                {-5, 3, -125},
                {2, 10, 1024},
                {-2, 10, 1024}
        });
    }

    @Test
    public void powTest() throws Exception {
        assertEquals(Pow.pow(a, b), expected);
    }

    @Parameter(0)
    public int a;

    @Parameter(1)
    public int b;

    @Parameter(2)
    public int expected;
}
